###
GET http://localhost:3010/ 

### 
POST http://localhost:3010/register 
Content-Type: application/json 

{
    "userName":"bhargav",
    "password":"bhargav@123"
}

### 
POST http://localhost:3010/login 
Content-Type: application/json 

{
    "userName":"sasi",
    "password":"sasidhar@123"
}